---
application:
  name: "lavalink"
  project: "Lavalink"
  publicly_accessible: true
  port: 8080
  organization: "QoveryCommunity"
routers:
- name: "main-lavalink"
  routes:
  - application_name: "lavalink"
    paths:
    - "/*"
